# Version catalog updates generated at 2023-03-15T11:59:01.047298
#
# Contents of this file will be applied to libs.versions.toml when running versionCatalogApplyUpdates.
#
# Comments will not be applied to the version catalog when updating.
# To prevent a version upgrade, comment out the entry or remove it.
#
[libraries]
# From version 1.1.5 --> 2.0.2
android-tools-desugar-jdk-libs = "com.android.tools:desugar_jdk_libs:2.0.2"
# From version 1.6.1 --> 1.8.0-alpha02
androidx-activity-compose = "androidx.activity:activity-compose:1.8.0-alpha02"
# From version 1.0.1 --> 1.1.0-alpha08
androidx-compose-material3 = "androidx.compose.material3:material3:1.1.0-alpha08"
# From version 1.3.3 --> 1.4.0-rc01
androidx-compose-ui = "androidx.compose.ui:ui:1.4.0-rc01"
# From version 1.3.3 --> 1.4.0-rc01
androidx-compose-ui-test-junit4 = "androidx.compose.ui:ui-test-junit4:1.4.0-rc01"
# From version 1.3.3 --> 1.4.0-rc01
androidx-compose-ui-test-manifest = "androidx.compose.ui:ui-test-manifest:1.4.0-rc01"
# From version 1.3.3 --> 1.4.0-rc01
androidx-compose-ui-tooling = "androidx.compose.ui:ui-tooling:1.4.0-rc01"
# From version 1.3.3 --> 1.4.0-rc01
androidx-compose-ui-tooling-preview = "androidx.compose.ui:ui-tooling-preview:1.4.0-rc01"
# From version 1.0.1 --> 1.1.0-alpha01
androidx-documentfile = "androidx.documentfile:documentfile:1.1.0-alpha01"
# From version 1.0.0 --> 1.1.0-alpha01
androidx-hilt-navigation-compose = "androidx.hilt:hilt-navigation-compose:1.1.0-alpha01"
# From version 2.5.3 --> 2.6.0-alpha07
androidx-navigation-compose = "androidx.navigation:navigation-compose:2.6.0-alpha07"
# From version 1.5.2 --> 1.5.3-alpha01
androidx-test-runner = "androidx.test:runner:1.5.3-alpha01"
# From version 1.6.4 --> 1.7.0-Beta
kotlinx-coroutines-android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.0-Beta"
# From version 1.6.4 --> 1.7.0-Beta
kotlinx-coroutines-test = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.7.0-Beta"

[plugins]
# From version 7.4.2 --> 8.1.0-alpha09
android-application = "com.android.application:8.1.0-alpha09"
# From version 7.4.2 --> 8.1.0-alpha09
android-library = "com.android.library:8.1.0-alpha09"
# From version 1.8.10 --> 1.8.20-RC
kotlin-android = "org.jetbrains.kotlin.android:1.8.20-RC"
# From version 1.8.10 --> 1.8.20-RC
kotlin-kapt = "org.jetbrains.kotlin.kapt:1.8.20-RC"
# From version 1.8.10 --> 1.8.20-RC
kotlin-parcelize = "org.jetbrains.kotlin.plugin.parcelize:1.8.20-RC"
# From version 1.8.10 --> 1.8.20-RC
kotlin-serialization = "org.jetbrains.kotlin.plugin.serialization:1.8.20-RC"
# From version 1.8.10-1.0.9 --> 1.8.20-RC-1.0.9
ksp = "com.google.devtools.ksp:1.8.20-RC-1.0.9"
